CREATE TABLE iceberg.silver.service_report (
    report_id INT,
    service_request_id INT,
    year INT,
    report_type STRING,
    status STRING,
    op STRING,
    version STRING,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    signed_at TIMESTAMP,
    author_id INT,
    company_tin STRING,
    company_name STRING,
    certificate_number STRING,
    oked STRING,
    residents_count BIGINT,
    nonresidents_count BIGINT,
    gph_count BIGINT,
    income_total BIGINT,
    income_international BIGINT,
    finance_source_increase_authorized_capital BIGINT,
    main_capital_investments BIGINT,
    finance_source_loan BIGINT,
    finance_source_loan_foreign BIGINT,
    finance_source_government BIGINT,
    finance_source_investment BIGINT,
    investor_amount BIGINT,
    investor_country_company STRING,
    tax_incentives BIGINT,
    tax_incentives_kpn BIGINT,
    tax_incentives_nds BIGINT,
    tax_incentives_ipn BIGINT,
    tax_incentives_sn BIGINT,
    etl_loaded_at TIMESTAMP
)
USING iceberg
PARTITIONED BY (year);